### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'model-wemb-msr/logs/dev/1.temp'

### ISSUE THREAD

**Issue by Jingyilang** [chqiwang/convseg#6]
When I use word ebedding(word_window==4), I encountered this error ：

> Traceback (most recent call last):
  File "train.py", line 91, in <module>
    max_epoches=args.max_epoches)
  File "/home/czy/Pycode/MasterPaper/code/convseg-master/tagger.py", line 440, in train
    log_dir + '/dev', epoch)
  File "/home/czy/Pycode/MasterPaper/code/convseg-master/cws.py", line 181, in evaluator
    eval_lines = [l.rstrip() for l in codecs.open(temp_path, 'r', 'utf8')]
  File "/home/czy/env/.virtualenvs/keras/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'model-wemb-msr/logs/dev/1.temp'

Can you tell me how to solve this problem? Thanks!

**Comment by chqiwang** [comment]
can u show me the cmd you use?

**Comment by Jingyilang** [comment]
Thanks for your reply!
Everything is ok while cmd is 

> ./train_cws.sh msr 0
However, That error happens while cmd is

>  ./train_cws_wemb.sh msr 0
I don't know what happened.

**Comment by Jingyilang** [comment]
> can u show me the cmd you use?

Thanks for your reply!
Everything is ok while cmd is

./train_cws.sh msr 0
However, That error happens while cmd is
./train_cws_wemb.sh msr 0
I don't know what happened.

**Comment by Jingyilang** [comment]
> can you paste all log message when you run the cmd? not only the traceback.

> 2018-12-11 17:58:54.176672: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2018-12-11 17:58:54.176681: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2018-12-11 17:58:54.176691: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
/home/czy/env/.virtualenvs/keras/local/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "train.py", line 91, in <module>
    max_epoches=args.max_epoches)
  File "/home/czy/Pycode/MasterPaper/code/convseg-master/tagger.py", line 440, in train
    log_dir + '/dev', epoch)
  File "/home/czy/Pycode/MasterPaper/code/convseg-master/cws.py", line 186, in evaluator
    eval_lines = [l.rstrip() for l in codecs.open(temp_path, 'r', 'utf8')]
  File "/home/czy/env/.virtualenvs/keras/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'model-wemb-msr/logs/dev/1.temp'

These are all  content in stderr.txt. I think there is no import information except traceback.

**Comment by Jingyilang** [comment]
> can you paste all log message when you run the cmd? not only the traceback.

There are only 1.ref and 1.pred in the logs/dev

**Comment by Jingyilang** [comment]
> can you paste all log message when you run the cmd? not only the traceback.

> Namespace(active_type='glu', batch_size=64, channels=200, dev_path='data/datasets/sighan2005-msr/dev.txt', dropout_emb=0.2, dropout_hidden=0.2, emb_size=200, eval_batch_size=640, fix_word_emb=0, hidden_layers=5, kernel_size=3, lamd=0, max_epoches=2, model_root='model-wemb-msr', optimizer='adam_0.001', pre_trained_emb_path='data/embeddings/news_tensite.w2v200', pre_trained_word_emb_path='data/embeddings/news_tensite.msr.words.w2v50', reserve_all_word_emb=0, task='cws', test_path='data/datasets/sighan2005-msr/test.txt', training_path='data/datasets/sighan2005-msr/train.txt', use_bn=1, use_crf=1, use_wn=1, word_emb_size=50, word_window=4)
Preparing data...Finished.
Start building the network...Finished.
Finished.
Start training the network...
5062 of 5101 character embeddings were loaded from pre-trained.
89703 of 89705 word embeddings were loaded from pre-trained.
Starting epoch 1...
  Step 50, current cost 10.059709, average cost 25.380704
  Step 100, current cost 7.034269, average cost 17.235078
  Step 150, current cost 4.893725, average cost 13.554557
  Step 200, current cost 5.187340, average cost 11.405232
  Step 250, current cost 2.829161, average cost 9.989628
  Step 300, current cost 3.974014, average cost 8.953159
  Step 350, current cost 2.673702, average cost 8.177753
  Step 400, current cost 3.015410, average cost 7.560520
  Step 450, current cost 3.560460, average cost 7.055582
  Step 500, current cost 1.829349, average cost 6.641980
  Step 550, current cost 1.939968, average cost 6.327397
  Step 600, current cost 2.579545, average cost 6.022282
  Step 650, current cost 1.579401, average cost 5.747525
  Step 700, current cost 2.500479, average cost 5.507219
  Step 750, current cost 3.356592, average cost 5.296968
  Step 800, current cost 3.276520, average cost 5.104576
  Step 850, current cost 3.031386, average cost 4.929337
  Step 900, current cost 1.005395, average cost 4.763488
  Step 950, current cost 1.884085, average cost 4.618178
  Step 1000, current cost 1.654177, average cost 4.482917
  Step 1050, current cost 1.752389, average cost 4.357124
  Step 1100, current cost 1.750034, average cost 4.237533
  Step 1150, current cost 1.478059, average cost 4.135781
  Step 1200, current cost 1.511727, average cost 4.031427
  Step 1250, current cost 1.303555, average cost 3.937180
Epoch 1 finished. Time: 384s Cost: 3.906361

These are content in the stdout.txt

**Comment by chqiwang** [comment]
I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?

**Comment by Jingyilang** [comment]
> I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?

Ok. I just download the code again because I suspect I changed something and execute the cmd 

> ./train_cws_wemb.sh msr 0

That error comes up again. So this should be an error in the original code itself. 
If I find anything I'll report it here.

**Comment by Jingyilang** [comment]
> I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?

That statement is NOT successfully executed by  ./train_cws_wemb.sh msr 0. It is sooooo weird.

**Comment by Jingyilang** [comment]
> I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?

Before that statement, I print the temp_path and the path of 1.tmep is correct too.

**Comment by Jingyilang** [comment]
> > I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?
> 
> Ok. I just download the code again because I suspect I changed something and execute the cmd
> 
> > ./train_cws_wemb.sh msr 0
> 
> That error comes up again. So this should be an error in the original code itself.
> If I find anything I'll report it here.

I set word_window==0 in the train_cws_wemb.sh. Everything is OK. How could the size of word_window effect the execution of that statement?

**Comment by Jingyilang** [comment]
> I see the log. this is very weird because this statement https://github.com/chqiwang/convseg/blob/master/cws.py#L177 will create the temp file. can you debug to see if this statement is successfully executed?

That statement is successfully executed while I set word_window==0/1/2/3. What's wrong with word_window==4?  It's really interesting!

**Comment by chqiwang** [comment]
this is so wried... can u check if anything is wrong  in *.pred and *.ref? by the way, word_window set to 3 or 4 maybe not influence the final performance too much. you can run with 3 first..

**Comment by Jingyilang** [comment]
> this is so wried... can u check if anything is wrong in *.pred and *.ref? by the way, word_window set to 3 or 4 maybe not influence the final performance too much. you can run with 3 first..

OK. Thanks for your reply again!

**Comment by Jingyilang** [comment]
> you're welcome. if you have any result, please put it here. glad to hear

In your paper, you show that when the number of network layers is increased to 5, the performance of the model does not increase with the increase in the number of  layers. Can you tell me if you've tried to increase hidden state?  What was the performance?

**Comment by chqiwang** [comment]
> > you're welcome. if you have any result, please put it here. glad to hear
> 
> In your paper, you show that when the number of network layers is increased to 5, the performance of the model does not increase with the increase in the number of layers. Can you tell me if you've tried to increase hidden state? What was the performance?

I gave the performance with different layers in Figure~5.

**Comment by Jingyilang** [comment]
> > > you're welcome. if you have any result, please put it here. glad to hear
> > 
> > 
> > In your paper, you show that when the number of network layers is increased to 5, the performance of the model does not increase with the increase in the number of layers. Can you tell me if you've tried to increase hidden state? What was the performance?
> 
> I gave the performance with different layers in Figure~5.

I did noticed figure 5. The FIgure 5 show the scores on dev set and test set with respect to the number of layers. I mean have you explored the scores with respect to the number of the CHANNELS in each layer?
