### ISSUE TITLE
meet some problem in train.py

### ISSUE THREAD

**Issue by JACKOBE** [chqiwang/convseg#8]
When i run the code train.py 
![1](https://user-images.githubusercontent.com/26809794/50477504-a2917000-0a07-11e9-9fd9-c07a2a7c3f7e.jpg)

Problem:
TASK = __import__("args")
AttributeError: module 'args' has no attribute 'read_train_file'

**Comment by chqiwang** [comment]
you didnt fill in arguments. please follow the steps provided in README

**Comment by chqiwang** [comment]
add it seems you modify my code. please clone a new copy then follow steps

**Comment by JACKOBE** [comment]
I follow the steps and i met the former problem
![2](https://user-images.githubusercontent.com/26809794/50481313-c6f74780-0a1b-11e9-895f-518f440b492d.png)
When I edit the code   "TASK = __import__(args.task)" to escape the problem,it will also tell me that 'FlushFile' object has no attribute 'flush'
And  __import__() argument 1 must be str, not None

![3](https://user-images.githubusercontent.com/26809794/50481384-2b1a0b80-0a1c-11e9-8fca-c8654f3daec8.png)

I did not know it.
Thanks

**Comment by chqiwang** [comment]
please run the script train.sh in bash instead of pycharm

**Comment by chqiwang** [comment]
do not to run train.py directly
